default: &default
  host: 127.0.0.1
  username: postgres
  password: <%= ENV["my_postgres_password"] %>
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: recipe-development

test:
  <<: *default
  database: recipe-test

production:
  <<: *default
  database: recipe-production